apiVersion: v1
kind: Pod
metadata:
  name: test-connection
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: test-connection-container
      image: busybox
      command: ["sh", "-c"]
      args:
        - |
          for i in $(seq 1 10); do
            wget -O- q2-ex2.default.svc.cluster.local:80;
            sleep 1;
          done
      resources:
        {{- toYaml .Values.resources | nindent 12 }}
  restartPolicy: Never
